# Generated by Django 4.2 on 2023-05-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
